### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [zosiasz/zadanie-8.4#1]
- [x] [html] dodaj doctype
- [x] [html] usun niepotrzebne spacje z `<title>`
- [x] [js] usun komentarze - sa zbedne
- [x] [js] rozwin troche komunikat, ktory wypisujesz w konsoli podobnie jak w tresci zadania, obecnie jest troche ubogo i nie wiadomo o co chodzi: https://scr.hu/gLede4
